### ISSUE TITLE
validate.py does not require "state_or_territory"

### ISSUE THREAD

**Issue by edmullen** [18F/dsnap_rules#1]
In new_rules/new_rules/validate.py, isn't "state_or_territory" necessary to correctly determine income eligibility?

I see "is_authorized_representative" is also not required, which seems correct.

**Comment by vrajmohan** [comment]
Good point. I was vacillating on the `state_or_territory` being an attribute of the request vs configuration and did't commit to one way or another.

**Comment by vrajmohan** [comment]
We'll eliminate this field from the request and look it up in the backend using the DR# - see #11.
