### ISSUE TITLE
Indicating a specific disaster

### ISSUE THREAD

**Issue by edmullen** [18F/dsnap_rules#11]
(This issue was spawned out of https://github.com/18F/new_rules/issues/3#issuecomment-434056982_)

The service should be able to serve many different states/disasters within the same instance. So the one service should be able to receive concurrent requests from, for example, hurricane responses in FL and NC and wildfire responses in Southern CA and an earthquake in Northern CA. This is central to the notion. 

I think there are a number of implications to this. The `worked_in_disaster_area_is_dnsap_eligible` configuration described in #3 provides one example. This would need a per-disaster configuration. 

Another implication is we may need some indication of which disaster the request is in response to. How do we tell the difference between two unrelated D-SNAPs with a single state such as CA.

There are likely others, but I wanted to mention that as it seems fundamental.

**Comment by vrajmohan** [comment]
Eliot and I discussed this - we would like to use the FEMA issued Disaster Request numbers (e.g., [DR-4393](https://www.fema.gov/disaster/4393)). These are unique to a disaster and to a state, ie, Hurricane Florence would have different DR numbers for North Carolina vs South Carolina.

**Comment by vrajmohan** [comment]
Fixed through https://github.com/18F/dsnap_rules/commit/4a735530dd44a0182860d025506ad75dfadd6beb.
