### ISSUE TITLE
Disaster Standard Expense Deduction

### ISSUE THREAD

**Issue by edmullen** [18F/dsnap_rules#8]
Creating an issue for the rules around Disaster Standard Expense Deduction. See [p17 and p39 Disaster SNAP Guidance](https://fns-prod.azureedge.net/sites/default/files/D-SNAP_handbook_0.pdf)

**Comment by EliotDK-USDA-FNS** [comment]
Also see [last page of the FY19 D-SNAP Income Standards](https://fns-prod.azureedge.net/sites/default/files/snap/FY2019-DSNAP-IncomeEligibilityStandards.pdf). Essentially, as long as a household has over $100 in disaster expenses, and they meet the final income limit for their household size, they are eligible.

The income limit for each household size is greater than under DGIL, which is the trade off for not having to manually calculate disaster expenses.
